### ISSUE TITLE
setsid not available to the shell on BSD

### ISSUE THREAD

**Issue by iillyyaa** [jsbronder/dbenv#3]
Makefile runs tests as session group leader, and uses Linux command setsid to do that. However, setsid command is not available on BSD (FreeBSD 10/11, Mac OS X).

Looks like removing setsid from the Makefile doesn't "just work", because test/base.sh assumes that it is the process group leader and tries to kill the process group that matches its own PID. This of course fails, since there is no such PGID.

**Comment by jsbronder** [comment]
Fixed by you in #4
